In [1]:
import numpy as np

In [2]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [3]:
b = np.ones((2,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
type(a[0])

numpy.float64

In [5]:
b.dtype

dtype('float64')

In [2]:
c = np.empty(10)
c

NameError: name 'np' is not defined

In [1]:
c.shape =(2,5)
#cannot reshape array of size 10 into shape (2,4)
c.ndim

NameError: name 'c' is not defined

In [8]:
d = np.linspace(3,20,5)
d

array([ 3.  ,  7.25, 11.5 , 15.75, 20.  ])

In [9]:
e = np.arange(3,20,5)
e

array([ 3,  8, 13, 18])

In [10]:
f = np.array((10,20,30,40,50))
f

array([10, 20, 30, 40, 50])

In [11]:
python_list = [[1,2,3,4,5],[6,7,8,9,10]]
g = np.array((python_list))
g

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
g.shape

(2, 5)

In [13]:
h = np.random.randint(10, size=5)
i = np.random.randint(10)
h

array([9, 3, 4, 3, 8])

In [14]:
h[0]

9

In [15]:
h[1:5]

array([3, 4, 3, 8])

In [16]:
h[-2]

3

In [17]:
h > 3

array([ True, False,  True, False,  True])

In [18]:
h [h>3]

array([9, 4, 8])

In [19]:
h*2

array([18,  6,  8,  6, 16])

In [20]:
python_list *2

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [21]:
h @ h # dot product

179

### Where Function:

In [22]:
# np.where(condition,True,False)
i = np.array([1,2,3,4,5,6,7,8,9])
j = np.array([8,7,3,6,8,4,2,1,9])

In [23]:
np.where(i>j,i,j)

array([8, 7, 3, 6, 8, 6, 7, 8, 9])

In [24]:
result = np.array([30,50,60,80,25,95,90,63])
np.where(result>40,"Pass","Fail")

array(['Fail', 'Pass', 'Pass', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass'],
      dtype='<U4')

### Numpy Stats & Maths Function:

In [25]:
k = np.array([1,2,3,4,5,6,7,8,9])
k.mean()

5.0

In [26]:
k.cumsum() # Cumutive Sum

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [27]:
k.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [28]:
l = k>5

In [29]:
l.sum() # how many true:

4

In [30]:
l.any() # Any One True ?

True

In [31]:
l.all()  # All values True ?

False

In [32]:
# Sorting:
m = np.array([1,4,7,9,5,3,6,2,8])
m.sort()
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# Unique Element:
n = np.random.randint(19,size=9)
n

array([ 2,  2,  5,  4, 17,  6, 10,  0,  5])

In [34]:
np.unique(n)

array([ 0,  2,  4,  5,  6, 10, 17])

### Save Function:

In [35]:
besties = ["Abid", "Nzr-e-Jawad", "Umair", "Shahzaib", "Faisal"]
classmates = ["Zamran", "Ateeq", "Hamdan", "Danish", "Mohsin"]

In [36]:
np.save("besties.npy", besties)
b1 = np.load("besties.npy")
b1

array(['Abid', 'Nzr-e-Jawad', 'Umair', 'Shahzaib', 'Faisal'], dtype='<U11')

In [37]:
np.savez("both", besties=besties, classmates=classmates)
b2 = np.load("both.npz")
b2 # Concedure as dict,

In [38]:
b2["besties"] # access using keys

array(['Abid', 'Nzr-e-Jawad', 'Umair', 'Shahzaib', 'Faisal'], dtype='<U11')

### Numpy Linear Algebra:

In [39]:
# Dot Product of 2 Vectors
o = np.array([1,2,3])
p = np.array([4,5,6])

In [40]:
print(np.dot(o,p))
print(np.dot(p,o))

32
32


In [41]:
# Matrix and vector:
q = np.array([[1,2,3],[4,5,6]])
q

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.dot(q,o)

array([14, 32])

In [43]:
# Transpose of a Matrix:
np.transpose(q)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
# identity of matrix:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
# inverse of Matrix
r = np.array([[1,2,3],[10,5,6],[7,8,9]])
r_inv = np.linalg.inv(r)
r_inv

array([[-0.08333333,  0.16666667, -0.08333333],
       [-1.33333333, -0.33333333,  0.66666667],
       [ 1.25      ,  0.16666667, -0.41666667]])

In [46]:
# Matrix Multiplication:
np.dot(r,r_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
r@r_inv # just jupyter magical cmd

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
# Trace of Matrix:
print(np.trace(q))

6


In [49]:
# Determinant of Matrix:
s = np.array([[3,4],[5,6]])
np.linalg.det(s)

-2.0000000000000013

### Pseudo Random Module & Functions:

In [50]:
np.random.randint(100,size=(3,2))

array([[50, 22],
       [65, 34],
       [84, 74]])

In [51]:
np.random.normal(9,size=(3,10))

array([[11.61201486, 10.05254883,  7.56621896, 10.09765291,  7.71613566,
         7.15046478,  9.62272602,  8.64259757, 11.01448384,  6.78752198],
       [10.30584278,  9.56616139,  9.05241983,  8.51587044,  9.59489469,
         7.91605566,  7.62635021,  8.63404072,  9.00010592,  8.69132038],
       [ 8.36053305,  9.42687259,  8.33666599,  8.87156446,  8.29104042,
         8.20068014,  9.89212842,  7.80496825,  8.08281364, 10.86272237]])

In [52]:
np.random.gamma(3, size=10)

array([2.74372449, 4.32043157, 4.19595199, 1.09559653, 1.4821466 ,
       3.46315024, 1.90143611, 3.69235338, 2.13934865, 2.5009387 ])

In [53]:
np.random.seed(10)

In [54]:
np.random.gamma(3, size=10)

array([5.48572926, 4.01355368, 3.8154306 , 1.65514449, 3.1241686 ,
       2.84788227, 3.43814096, 5.15314164, 3.05771307, 3.46162299])

### Reshape:

In [55]:
t = np.arange(1,13) # 12 Elements

In [56]:
t.reshape(2,6)  # 2*6 = 12

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [57]:
t.reshape(3,4) # 3*4 = 12

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
# Fortran Order/ F Order for Column, C Order for Row:
t.reshape(3,4, order='c')

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
t.reshape(3,4, order="f")

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [65]:
u = t.reshape(2,3,2, order='c')

In [62]:
t.reshape(2,3,2, order="f")

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

### Ravel and Flatten:

In [63]:
# Ravel or Flatten Used For: Making Multiple Dimension DataSet into Single Dimension,
t.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
u.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Concatenate & Spliting:

In [67]:
v = np.arange(1,5)
w = np.arange(6,10)
np.concatenate((v,w), axis=0)

array([1, 2, 3, 4, 6, 7, 8, 9])

In [68]:
np.hstack((v,w)) # Horizontal

array([1, 2, 3, 4, 6, 7, 8, 9])

In [69]:
np.vstack((v,w)) # Verticle

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [70]:
x=np.arange(1,15)
np.split(x,[3,6])

[array([1, 2, 3]), array([4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]

In [71]:
np.split(x,[3,6,7])

[array([1, 2, 3]),
 array([4, 5, 6]),
 array([7]),
 array([ 8,  9, 10, 11, 12, 13, 14])]

### Tile & Repeat:

In [73]:
y = np.array([1,5,7,8])
np.repeat(y,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [74]:
np.tile(a,3)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])