In [1]:
import numpy as np

In [15]:
x = np.arange(1,13,dtype=int).reshape(6,2)
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [17]:
 x =  np.arange(10,37,dtype=np.float64).reshape(3,3,3)
x

array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]],

       [[28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]]])

In [20]:
a = np.arange(1, 100*10+1).reshape((100,10))

In [23]:
np.zeros(20).reshape(4,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
arr = np.zeros(10)
arr[4] = 10
arr[7] = 20
arr

array([ 0.,  0.,  0.,  0., 10.,  0.,  0., 20.,  0.,  0.])

In [34]:
np.zeros(4, dtype=np.int64)

array([0, 0, 0, 0])